ALTER TABLE "campaigns"
  ADD COLUMN IF NOT EXISTS "name" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "listIds" TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "segmentIds" TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "excludeListIds" TEXT[] DEFAULT '{}';
