#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Continuum — one-command setup script
# Usage: bash scripts/setup.sh
#
# What it does:
#   1. Prompts for the 4 credentials you paste from dashboards
#   2. Generates API_KEY_SALT automatically
#   3. Writes .env
#   4. Installs npm deps
#   5. Runs prisma generate + migrate:deploy  (creates all 9 tables in Supabase)
#   6. Seeds the disposable-domain blocklist
#   7. Creates your first API key and prints it
#   8. Prints the Railway deploy commands to copy-paste
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${BLUE}${BOLD}╔══════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}${BOLD}║        Continuum Setup Script            ║${NC}"
  echo -e "${BLUE}${BOLD}╚══════════════════════════════════════════╝${NC}"
  echo ""
}

step() { echo -e "\n${GREEN}▶ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠  $1${NC}"; }
info() { echo -e "   ${BLUE}$1${NC}"; }
ok()   { echo -e "   ${GREEN}✓ $1${NC}"; }
die()  { echo -e "${RED}✗ $1${NC}"; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed. Install it first."
}

# ─── Preflight ────────────────────────────────────────────────────────────────

banner

require_cmd node
require_cmd npm
require_cmd openssl

NODE_VER=$(node -e "console.log(process.versions.node.split('.')[0])")
if [ "$NODE_VER" -lt 20 ]; then
  die "Node.js 20+ is required. You have Node $NODE_VER. Install from https://nodejs.org"
fi
ok "Node.js $(node --version) detected"

if [ -f .env ]; then
  warn ".env already exists. Back it up? (y/n)"
  read -r BACKUP
  if [[ "$BACKUP" == "y" ]]; then
    cp .env ".env.backup.$(date +%s)"
    ok "Backed up to .env.backup.*"
  fi
fi

# ─── Collect credentials ──────────────────────────────────────────────────────

step "Collecting credentials — you need 4 values from 2 dashboards"
echo ""
echo -e "${BOLD}SUPABASE (supabase.com → your project):${NC}"
echo "  Settings → Database → Connection string (URI mode)"
echo "  Settings → API → service_role key"
echo "  Settings → API → Project URL"
echo ""

read -rp "  Paste DATABASE_URL (postgresql://...): " DATABASE_URL
[[ "$DATABASE_URL" == postgresql* ]] || die "Must start with postgresql://"

read -rp "  Paste SUPABASE_URL (https://xxx.supabase.co): " SUPABASE_URL
[[ "$SUPABASE_URL" == https://* ]] || die "Must start with https://"

read -rsp "  Paste SUPABASE_SERVICE_ROLE_KEY (eyJ...): " SUPABASE_SERVICE_ROLE_KEY
echo ""
[[ ${#SUPABASE_SERVICE_ROLE_KEY} -gt 20 ]] || die "Service role key looks too short"

echo ""
echo -e "${BOLD}UPSTASH REDIS (upstash.com → your database):${NC}"
echo "  Details tab → Redis URL (starts with rediss://)"
echo ""

read -rsp "  Paste REDIS_URL (rediss://...): " REDIS_URL
echo ""
[[ "$REDIS_URL" == redis* ]] || die "Must start with redis:// or rediss://"

echo ""
echo -e "${BOLD}DOMAIN (your domain for SMTP HELO):${NC}"
echo "  Use any domain you own that has a DNS A record."
echo "  It doesn't need to send email — just needs to exist in DNS."
echo "  Example: verify.yourdomain.com  or  api.yourdomain.com"
echo ""

read -rp "  Enter your SMTP_HELO_DOMAIN: " SMTP_HELO_DOMAIN
[[ -n "$SMTP_HELO_DOMAIN" ]] || SMTP_HELO_DOMAIN="localhost"

echo ""
echo -e "${BOLD}SMTP check:${NC}"
echo "  Railway/Render/Fly.io block port 25 → answer 'false'"
echo "  Hetzner/DigitalOcean VPS → answer 'true'"
read -rp "  Enable SMTP probing? (true/false) [false]: " SMTP_ENABLED
SMTP_ENABLED="${SMTP_ENABLED:-false}"

# ─── Generate secrets ─────────────────────────────────────────────────────────

API_KEY_SALT=$(openssl rand -hex 32)
ok "Generated API_KEY_SALT (32 random bytes)"

# ─── Write .env ──────────────────────────────────────────────────────────────

step "Writing .env"

cat > .env << ENVEOF
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
NODE_ENV=production
PORT=3000
HOST=0.0.0.0

DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}

SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

STORAGE_BUCKET_UPLOADS=continuum-uploads
STORAGE_BUCKET_EXPORTS=continuum-exports

SMTP_CHECK_ENABLED=${SMTP_ENABLED}
SMTP_CHECK_TIMEOUT_MS=5000
SMTP_HELO_DOMAIN=${SMTP_HELO_DOMAIN}

DEFAULT_RATE_LIMIT_RPM=1000
WEBHOOK_MAX_ATTEMPTS=5
WEBHOOK_TIMEOUT_MS=10000

LOG_LEVEL=info
API_KEY_SALT=${API_KEY_SALT}
ENVEOF

ok ".env written"

# ─── Install deps ─────────────────────────────────────────────────────────────

step "Installing npm dependencies"
npm install --silent
ok "Dependencies installed"

# ─── Prisma generate ──────────────────────────────────────────────────────────

step "Generating Prisma client"
npx prisma generate --silent 2>/dev/null || \
  npx prisma generate 2>&1 | tail -3
ok "Prisma client generated"

# ─── Migrate ──────────────────────────────────────────────────────────────────

step "Running database migrations (creates all 9 tables in Supabase)"
info "Connecting to Supabase..."
npx prisma migrate deploy 2>&1 | tail -5
ok "Database schema applied"

# ─── Supabase Storage buckets ─────────────────────────────────────────────────

step "Creating Supabase Storage buckets"
info "Attempting to create buckets via Supabase API..."

# Use curl to create buckets via the Supabase Storage API
BUCKET_API="${SUPABASE_URL}/storage/v1/bucket"

create_bucket() {
  local NAME="$1"
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "$BUCKET_API" \
    -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"id\":\"${NAME}\",\"name\":\"${NAME}\",\"public\":false}")
  if [[ "$HTTP" == "200" || "$HTTP" == "201" ]]; then
    ok "Bucket '${NAME}' created"
  elif [[ "$HTTP" == "409" ]]; then
    ok "Bucket '${NAME}' already exists"
  else
    warn "Bucket '${NAME}' — HTTP ${HTTP} (may need manual creation in Supabase dashboard)"
  fi
}

create_bucket "continuum-uploads"
create_bucket "continuum-exports"

# ─── Disposable list ──────────────────────────────────────────────────────────

step "Seeding disposable domain blocklist"
if npx tsx scripts/update-disposable-list.ts 2>/dev/null; then
  ok "Blocklist updated from upstream"
else
  warn "Could not reach upstream (offline?). Using bundled seed list."
fi

# ─── First API key ────────────────────────────────────────────────────────────

step "Creating your first API key"
echo ""
npx tsx scripts/generate-api-key.ts --label "production" --rpm 1000
echo ""

# ─── Done ────────────────────────────────────────────────────────────────────

step "Setup complete!"

echo ""
echo -e "${BOLD}To start locally:${NC}"
echo "  npm run dev                  # API server (port 3000)"
echo "  npm run worker:bulk          # Bulk CSV worker"
echo "  npm run worker:monitor       # Email monitoring worker"
echo "  npm run worker:webhook       # Webhook delivery worker"
echo ""
echo -e "${BOLD}Test it:${NC}"
echo "  curl http://localhost:3000/health"
echo ""

# Railway deploy instructions
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}Deploy to Railway (run these commands):${NC}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  npm install -g @railway/cli"
echo "  railway login"
echo "  railway init"
echo "  railway up"
echo ""
echo "  Then in Railway dashboard → add 4 services (api + 3 workers)"
echo "  Run:  bash scripts/deploy-railway.sh   (next script)"
echo ""

# Write the .env values as a reminder
echo -e "${BOLD}Your .env is saved. Keep it secret — never commit it to git.${NC}"
echo ""
