/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard.accounts'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as DashboardApiReferenceRouteImport } from './routes/dashboard.api-reference'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard.audit-logs'
import { Route as DashboardAutomationsRouteImport } from './routes/dashboard.automations'
import { Route as DashboardBatchSendRouteImport } from './routes/dashboard.batch-send'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBrandKitRouteImport } from './routes/dashboard.brand-kit'
import { Route as DashboardBulkRouteImport } from './routes/dashboard.bulk'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardConnectorsRouteImport } from './routes/dashboard.connectors'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardDeliverabilityRouteImport } from './routes/dashboard.deliverability'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardFinderRouteImport } from './routes/dashboard.finder'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardInboxTestRouteImport } from './routes/dashboard.inbox-test'
import { Route as DashboardIpRouteImport } from './routes/dashboard.ip'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardListsRouteImport } from './routes/dashboard.lists'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardMailboxesRouteImport } from './routes/dashboard.mailboxes'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardMigrateRouteImport } from './routes/dashboard.migrate'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardOrganizationRouteImport } from './routes/dashboard.organization'
import { Route as DashboardPhoneRouteImport } from './routes/dashboard.phone'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard.playground'
import { Route as DashboardPrivacyRouteImport } from './routes/dashboard.privacy'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard.schedule'
import { Route as DashboardSegmentsRouteImport } from './routes/dashboard.segments'
import { Route as DashboardSequencesRouteImport } from './routes/dashboard.sequences'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSuppressionsRouteImport } from './routes/dashboard.suppressions'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardToolsRouteImport } from './routes/dashboard.tools'
import { Route as DashboardTransactionalRouteImport } from './routes/dashboard.transactional'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard.verify'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardWidgetRouteImport } from './routes/dashboard.widget'
import { Route as DashboardAccountsIdRouteImport } from './routes/dashboard.accounts.$id'
import { Route as DashboardLeadsIdRouteImport } from './routes/dashboard.leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiReferenceRoute = DashboardApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationsRoute = DashboardAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBatchSendRoute = DashboardBatchSendRouteImport.update({
  id: '/batch-send',
  path: '/batch-send',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandKitRoute = DashboardBrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBulkRoute = DashboardBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectorsRoute = DashboardConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliverabilityRoute = DashboardDeliverabilityRouteImport.update({
  id: '/deliverability',
  path: '/deliverability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinderRoute = DashboardFinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxTestRoute = DashboardInboxTestRouteImport.update({
  id: '/inbox-test',
  path: '/inbox-test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIpRoute = DashboardIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListsRoute = DashboardListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailboxesRoute = DashboardMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrateRoute = DashboardMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationRoute = DashboardOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhoneRoute = DashboardPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSegmentsRoute = DashboardSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSequencesRoute = DashboardSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuppressionsRoute = DashboardSuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsRoute = DashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionalRoute = DashboardTransactionalRouteImport.update({
  id: '/transactional',
  path: '/transactional',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetRoute = DashboardWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsIdRoute = DashboardAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAccountsRoute,
} as any)
const DashboardLeadsIdRoute = DashboardLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-reference': typeof DashboardApiReferenceRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/batch-send': typeof DashboardBatchSendRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/deliverability': typeof DashboardDeliverabilityRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/finder': typeof DashboardFinderRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inbox-test': typeof DashboardInboxTestRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/migrate': typeof DashboardMigrateRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/segments': typeof DashboardSegmentsRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppressions': typeof DashboardSuppressionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounts/$id': typeof DashboardAccountsIdRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-reference': typeof DashboardApiReferenceRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/batch-send': typeof DashboardBatchSendRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/deliverability': typeof DashboardDeliverabilityRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/finder': typeof DashboardFinderRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inbox-test': typeof DashboardInboxTestRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/migrate': typeof DashboardMigrateRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/segments': typeof DashboardSegmentsRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppressions': typeof DashboardSuppressionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accounts/$id': typeof DashboardAccountsIdRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/accounts': typeof DashboardAccountsRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-reference': typeof DashboardApiReferenceRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/automations': typeof DashboardAutomationsRoute
  '/dashboard/batch-send': typeof DashboardBatchSendRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-kit': typeof DashboardBrandKitRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/deliverability': typeof DashboardDeliverabilityRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/finder': typeof DashboardFinderRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/inbox-test': typeof DashboardInboxTestRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/migrate': typeof DashboardMigrateRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/organization': typeof DashboardOrganizationRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/segments': typeof DashboardSegmentsRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/suppressions': typeof DashboardSuppressionsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounts/$id': typeof DashboardAccountsIdRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/callback'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/api-reference'
    | '/dashboard/audit-logs'
    | '/dashboard/automations'
    | '/dashboard/batch-send'
    | '/dashboard/billing'
    | '/dashboard/brand-kit'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/connectors'
    | '/dashboard/contacts'
    | '/dashboard/deliverability'
    | '/dashboard/domains'
    | '/dashboard/finder'
    | '/dashboard/import'
    | '/dashboard/inbox'
    | '/dashboard/inbox-test'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/logs'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/migrate'
    | '/dashboard/monitoring'
    | '/dashboard/organization'
    | '/dashboard/phone'
    | '/dashboard/playground'
    | '/dashboard/privacy'
    | '/dashboard/schedule'
    | '/dashboard/segments'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/suppressions'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tools'
    | '/dashboard/transactional'
    | '/dashboard/usage'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard/widget'
    | '/dashboard/'
    | '/dashboard/accounts/$id'
    | '/dashboard/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/api-reference'
    | '/dashboard/audit-logs'
    | '/dashboard/automations'
    | '/dashboard/batch-send'
    | '/dashboard/billing'
    | '/dashboard/brand-kit'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/connectors'
    | '/dashboard/contacts'
    | '/dashboard/deliverability'
    | '/dashboard/domains'
    | '/dashboard/finder'
    | '/dashboard/import'
    | '/dashboard/inbox'
    | '/dashboard/inbox-test'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/logs'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/migrate'
    | '/dashboard/monitoring'
    | '/dashboard/organization'
    | '/dashboard/phone'
    | '/dashboard/playground'
    | '/dashboard/privacy'
    | '/dashboard/schedule'
    | '/dashboard/segments'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/suppressions'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tools'
    | '/dashboard/transactional'
    | '/dashboard/usage'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard/widget'
    | '/dashboard'
    | '/dashboard/accounts/$id'
    | '/dashboard/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/callback'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/accounts'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/api-reference'
    | '/dashboard/audit-logs'
    | '/dashboard/automations'
    | '/dashboard/batch-send'
    | '/dashboard/billing'
    | '/dashboard/brand-kit'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/connectors'
    | '/dashboard/contacts'
    | '/dashboard/deliverability'
    | '/dashboard/domains'
    | '/dashboard/finder'
    | '/dashboard/import'
    | '/dashboard/inbox'
    | '/dashboard/inbox-test'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/logs'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/migrate'
    | '/dashboard/monitoring'
    | '/dashboard/organization'
    | '/dashboard/phone'
    | '/dashboard/playground'
    | '/dashboard/privacy'
    | '/dashboard/schedule'
    | '/dashboard/segments'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/suppressions'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/templates'
    | '/dashboard/tools'
    | '/dashboard/transactional'
    | '/dashboard/usage'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard/widget'
    | '/dashboard/'
    | '/dashboard/accounts/$id'
    | '/dashboard/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-reference': {
      id: '/dashboard/api-reference'
      path: '/api-reference'
      fullPath: '/dashboard/api-reference'
      preLoaderRoute: typeof DashboardApiReferenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automations': {
      id: '/dashboard/automations'
      path: '/automations'
      fullPath: '/dashboard/automations'
      preLoaderRoute: typeof DashboardAutomationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/batch-send': {
      id: '/dashboard/batch-send'
      path: '/batch-send'
      fullPath: '/dashboard/batch-send'
      preLoaderRoute: typeof DashboardBatchSendRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-kit': {
      id: '/dashboard/brand-kit'
      path: '/brand-kit'
      fullPath: '/dashboard/brand-kit'
      preLoaderRoute: typeof DashboardBrandKitRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bulk': {
      id: '/dashboard/bulk'
      path: '/bulk'
      fullPath: '/dashboard/bulk'
      preLoaderRoute: typeof DashboardBulkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connectors': {
      id: '/dashboard/connectors'
      path: '/connectors'
      fullPath: '/dashboard/connectors'
      preLoaderRoute: typeof DashboardConnectorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deliverability': {
      id: '/dashboard/deliverability'
      path: '/deliverability'
      fullPath: '/dashboard/deliverability'
      preLoaderRoute: typeof DashboardDeliverabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finder': {
      id: '/dashboard/finder'
      path: '/finder'
      fullPath: '/dashboard/finder'
      preLoaderRoute: typeof DashboardFinderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox-test': {
      id: '/dashboard/inbox-test'
      path: '/inbox-test'
      fullPath: '/dashboard/inbox-test'
      preLoaderRoute: typeof DashboardInboxTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ip': {
      id: '/dashboard/ip'
      path: '/ip'
      fullPath: '/dashboard/ip'
      preLoaderRoute: typeof DashboardIpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lists': {
      id: '/dashboard/lists'
      path: '/lists'
      fullPath: '/dashboard/lists'
      preLoaderRoute: typeof DashboardListsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mailboxes': {
      id: '/dashboard/mailboxes'
      path: '/mailboxes'
      fullPath: '/dashboard/mailboxes'
      preLoaderRoute: typeof DashboardMailboxesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/migrate': {
      id: '/dashboard/migrate'
      path: '/migrate'
      fullPath: '/dashboard/migrate'
      preLoaderRoute: typeof DashboardMigrateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organization': {
      id: '/dashboard/organization'
      path: '/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof DashboardOrganizationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/phone': {
      id: '/dashboard/phone'
      path: '/phone'
      fullPath: '/dashboard/phone'
      preLoaderRoute: typeof DashboardPhoneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/privacy': {
      id: '/dashboard/privacy'
      path: '/privacy'
      fullPath: '/dashboard/privacy'
      preLoaderRoute: typeof DashboardPrivacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/segments': {
      id: '/dashboard/segments'
      path: '/segments'
      fullPath: '/dashboard/segments'
      preLoaderRoute: typeof DashboardSegmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sequences': {
      id: '/dashboard/sequences'
      path: '/sequences'
      fullPath: '/dashboard/sequences'
      preLoaderRoute: typeof DashboardSequencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/suppressions': {
      id: '/dashboard/suppressions'
      path: '/suppressions'
      fullPath: '/dashboard/suppressions'
      preLoaderRoute: typeof DashboardSuppressionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools': {
      id: '/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactional': {
      id: '/dashboard/transactional'
      path: '/transactional'
      fullPath: '/dashboard/transactional'
      preLoaderRoute: typeof DashboardTransactionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widget': {
      id: '/dashboard/widget'
      path: '/widget'
      fullPath: '/dashboard/widget'
      preLoaderRoute: typeof DashboardWidgetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts/$id': {
      id: '/dashboard/accounts/$id'
      path: '/$id'
      fullPath: '/dashboard/accounts/$id'
      preLoaderRoute: typeof DashboardAccountsIdRouteImport
      parentRoute: typeof DashboardAccountsRoute
    }
    '/dashboard/leads/$id': {
      id: '/dashboard/leads/$id'
      path: '/$id'
      fullPath: '/dashboard/leads/$id'
      preLoaderRoute: typeof DashboardLeadsIdRouteImport
      parentRoute: typeof DashboardLeadsRoute
    }
  }
}

interface DashboardAccountsRouteChildren {
  DashboardAccountsIdRoute: typeof DashboardAccountsIdRoute
}

const DashboardAccountsRouteChildren: DashboardAccountsRouteChildren = {
  DashboardAccountsIdRoute: DashboardAccountsIdRoute,
}

const DashboardAccountsRouteWithChildren =
  DashboardAccountsRoute._addFileChildren(DashboardAccountsRouteChildren)

interface DashboardLeadsRouteChildren {
  DashboardLeadsIdRoute: typeof DashboardLeadsIdRoute
}

const DashboardLeadsRouteChildren: DashboardLeadsRouteChildren = {
  DashboardLeadsIdRoute: DashboardLeadsIdRoute,
}

const DashboardLeadsRouteWithChildren = DashboardLeadsRoute._addFileChildren(
  DashboardLeadsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRouteWithChildren
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardApiReferenceRoute: typeof DashboardApiReferenceRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardAutomationsRoute: typeof DashboardAutomationsRoute
  DashboardBatchSendRoute: typeof DashboardBatchSendRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBrandKitRoute: typeof DashboardBrandKitRoute
  DashboardBulkRoute: typeof DashboardBulkRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardConnectorsRoute: typeof DashboardConnectorsRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardDeliverabilityRoute: typeof DashboardDeliverabilityRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardFinderRoute: typeof DashboardFinderRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardInboxTestRoute: typeof DashboardInboxTestRoute
  DashboardIpRoute: typeof DashboardIpRoute
  DashboardLeadsRoute: typeof DashboardLeadsRouteWithChildren
  DashboardListsRoute: typeof DashboardListsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMailboxesRoute: typeof DashboardMailboxesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMigrateRoute: typeof DashboardMigrateRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardOrganizationRoute: typeof DashboardOrganizationRoute
  DashboardPhoneRoute: typeof DashboardPhoneRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSegmentsRoute: typeof DashboardSegmentsRoute
  DashboardSequencesRoute: typeof DashboardSequencesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSuppressionsRoute: typeof DashboardSuppressionsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardToolsRoute: typeof DashboardToolsRoute
  DashboardTransactionalRoute: typeof DashboardTransactionalRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardWidgetRoute: typeof DashboardWidgetRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRouteWithChildren,
  DashboardAiRoute: DashboardAiRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardApiReferenceRoute: DashboardApiReferenceRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardAutomationsRoute: DashboardAutomationsRoute,
  DashboardBatchSendRoute: DashboardBatchSendRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBrandKitRoute: DashboardBrandKitRoute,
  DashboardBulkRoute: DashboardBulkRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardConnectorsRoute: DashboardConnectorsRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardDeliverabilityRoute: DashboardDeliverabilityRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardFinderRoute: DashboardFinderRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardInboxTestRoute: DashboardInboxTestRoute,
  DashboardIpRoute: DashboardIpRoute,
  DashboardLeadsRoute: DashboardLeadsRouteWithChildren,
  DashboardListsRoute: DashboardListsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMailboxesRoute: DashboardMailboxesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMigrateRoute: DashboardMigrateRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardOrganizationRoute: DashboardOrganizationRoute,
  DashboardPhoneRoute: DashboardPhoneRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSegmentsRoute: DashboardSegmentsRoute,
  DashboardSequencesRoute: DashboardSequencesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSuppressionsRoute: DashboardSuppressionsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardToolsRoute: DashboardToolsRoute,
  DashboardTransactionalRoute: DashboardTransactionalRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardWidgetRoute: DashboardWidgetRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
