/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardBulkRouteImport } from './routes/dashboard.bulk'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardIpRouteImport } from './routes/dashboard.ip'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardListsRouteImport } from './routes/dashboard.lists'
import { Route as DashboardMailboxesRouteImport } from './routes/dashboard.mailboxes'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardMonitoringRouteImport } from './routes/dashboard.monitoring'
import { Route as DashboardPhoneRouteImport } from './routes/dashboard.phone'
import { Route as DashboardSequencesRouteImport } from './routes/dashboard.sequences'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTransactionalRouteImport } from './routes/dashboard.transactional'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard.verify'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBulkRoute = DashboardBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIpRoute = DashboardIpRouteImport.update({
  id: '/ip',
  path: '/ip',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListsRoute = DashboardListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailboxesRoute = DashboardMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPhoneRoute = DashboardPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSequencesRoute = DashboardSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionalRoute = DashboardTransactionalRouteImport.update({
  id: '/transactional',
  path: '/transactional',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/ip': typeof DashboardIpRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/lists': typeof DashboardListsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/monitoring': typeof DashboardMonitoringRoute
  '/dashboard/phone': typeof DashboardPhoneRoute
  '/dashboard/sequences': typeof DashboardSequencesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/transactional': typeof DashboardTransactionalRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/domains'
    | '/dashboard/inbox'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/monitoring'
    | '/dashboard/phone'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/transactional'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/domains'
    | '/dashboard/inbox'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/monitoring'
    | '/dashboard/phone'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/transactional'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/api-keys'
    | '/dashboard/billing'
    | '/dashboard/bulk'
    | '/dashboard/campaigns'
    | '/dashboard/domains'
    | '/dashboard/inbox'
    | '/dashboard/ip'
    | '/dashboard/leads'
    | '/dashboard/lists'
    | '/dashboard/mailboxes'
    | '/dashboard/messages'
    | '/dashboard/monitoring'
    | '/dashboard/phone'
    | '/dashboard/sequences'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/transactional'
    | '/dashboard/verify'
    | '/dashboard/webhooks'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bulk': {
      id: '/dashboard/bulk'
      path: '/bulk'
      fullPath: '/dashboard/bulk'
      preLoaderRoute: typeof DashboardBulkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ip': {
      id: '/dashboard/ip'
      path: '/ip'
      fullPath: '/dashboard/ip'
      preLoaderRoute: typeof DashboardIpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lists': {
      id: '/dashboard/lists'
      path: '/lists'
      fullPath: '/dashboard/lists'
      preLoaderRoute: typeof DashboardListsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mailboxes': {
      id: '/dashboard/mailboxes'
      path: '/mailboxes'
      fullPath: '/dashboard/mailboxes'
      preLoaderRoute: typeof DashboardMailboxesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring': {
      id: '/dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/dashboard/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/phone': {
      id: '/dashboard/phone'
      path: '/phone'
      fullPath: '/dashboard/phone'
      preLoaderRoute: typeof DashboardPhoneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sequences': {
      id: '/dashboard/sequences'
      path: '/sequences'
      fullPath: '/dashboard/sequences'
      preLoaderRoute: typeof DashboardSequencesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactional': {
      id: '/dashboard/transactional'
      path: '/transactional'
      fullPath: '/dashboard/transactional'
      preLoaderRoute: typeof DashboardTransactionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBulkRoute: typeof DashboardBulkRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardIpRoute: typeof DashboardIpRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardListsRoute: typeof DashboardListsRoute
  DashboardMailboxesRoute: typeof DashboardMailboxesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardPhoneRoute: typeof DashboardPhoneRoute
  DashboardSequencesRoute: typeof DashboardSequencesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardTransactionalRoute: typeof DashboardTransactionalRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBulkRoute: DashboardBulkRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardIpRoute: DashboardIpRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardListsRoute: DashboardListsRoute,
  DashboardMailboxesRoute: DashboardMailboxesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardPhoneRoute: DashboardPhoneRoute,
  DashboardSequencesRoute: DashboardSequencesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardTransactionalRoute: DashboardTransactionalRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
